[package]

name = "marksman_escape"
version = "0.1.0"
authors = ["Simonas Kazlauskas <git@kazlauskas.me>"]
description = "HTML-escape strings"
keywords = ["html", "escape", "sanitise", "sanitize"]
license = "ISC"
